# N_ROWS = 6  # Maze's width
# N_COLS = 15  # Maze's height

maze_ex = [[{'N': False, 'S': True, 'W': True, 'E': True}, {'N': False, 'S': True, 'W': True, 'E': True},
            {'N': False, 'S': True, 'W': True, 'E': True}, {'N': False, 'S': True, 'W': True, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': True}, {'N': True, 'S': True, 'W': True, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': False}, {'N': True, 'S': True, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': True}],
           [{'N': False, 'S': False, 'W': True, 'E': True}, {'N': False, 'S': False, 'W': True, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': True}, {'N': False, 'S': True, 'W': True, 'E': False},
            {'N': False, 'S': False, 'W': False, 'E': True}, {'N': True, 'S': True, 'W': True, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': True}, {'N': False, 'S': False, 'W': True, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': False, 'S': False, 'W': False, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': True}],
           [{'N': False, 'S': False, 'W': True, 'E': True}, {'N': True, 'S': False, 'W': True, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': True},
            {'N': False, 'S': True, 'W': True, 'E': True}, {'N': False, 'S': True, 'W': True, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': False}, {'N': False, 'S': False, 'W': False, 'E': True},
            {'N': False, 'S': False, 'W': True, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': False},
            {'N': True, 'S': False, 'W': False, 'E': False}, {'N': False, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': False, 'S': False, 'W': True, 'E': True}],
           [{'N': False, 'S': False, 'W': True, 'E': True}, {'N': True, 'S': True, 'W': True, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': True}, {'N': False, 'S': False, 'W': True, 'E': False},
            {'N': True, 'S': False, 'W': False, 'E': False}, {'N': False, 'S': False, 'W': False, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': False, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': True}, {'N': True, 'S': False, 'W': True, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': True}, {'N': True, 'S': False, 'W': True, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': True}],
           [{'N': False, 'S': False, 'W': True, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': False},
            {'N': False, 'S': False, 'W': False, 'E': True}, {'N': False, 'S': False, 'W': True, 'E': True},
            {'N': False, 'S': True, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': False, 'S': True, 'W': True, 'E': True}, {'N': False, 'S': False, 'W': True, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': False, 'S': True, 'W': False, 'E': False},
            {'N': True, 'S': True, 'W': False, 'E': False}, {'N': True, 'S': True, 'W': False, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': False},
            {'N': False, 'S': True, 'W': False, 'E': True}],
           [{'N': True, 'S': False, 'W': True, 'E': True}, {'N': True, 'S': False, 'W': True, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': False}, {'N': True, 'S': True, 'W': False, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': True, 'S': False, 'W': False, 'E': True},
            {'N': True, 'S': True, 'W': True, 'E': False}, {'N': True, 'S': True, 'W': False, 'E': False},
            {'N': True, 'S': False, 'W': False, 'E': False}, {'N': True, 'S': True, 'W': False, 'E': True},
            {'N': True, 'S': False, 'W': True, 'E': True, 'EXIT': True}]]

path_ex = [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (5, 2), (5, 3), (4, 3), (3, 3), (3, 4), (3, 5),
           (3, 6), (3, 7), (2, 7), (1, 7), (1, 8), (2, 8), (2, 9), (2, 10), (2, 11), (3, 11), (3, 12), (3, 13), (4, 13),
           (4, 14), (5, 14)]

visited_ex = [[True, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
              [True, False, False, False, False, False, False, True, True, False, False, False, False, False, False],
              [True, False, False, False, False, False, False, True, True, True, True, True, False, False, False],
              [True, False, False, True, True, True, True, True, True, True, True, True, True, True, False],
              [True, True, True, True, True, True, True, True, False, False, False, False, False, True, True],
              [True, True, True, True, True, True, True, True, False, False, False, False, False, False, True]]
